name: diss
channels:
- conda-forge
- pytorch
dependencies:
- accelerate
- datasets
- jupyterlab
- numpy
- pandas
- python=3.10
- pytorch
- scikit-learn
- submitit
- torchaudio
- torchvision
- transformers
